### ISSUE TITLE
Info tab shows for any recipe.

### ISSUE THREAD

**Issue by ZeroLevels** [GoryMoon/InfoDataPack#1]
Anyways, I added some info to the following blocks:
**data/minecraft/jei_info/stick.json** `{ "items":["minecraft:stick"], "infos":["What's brown and sticky?"] }`
**data/minecraft/jei_info/piston.json** `{ "items":["minecraft:piston"], "infos":["You did WHAT now?"] }`

### **What was expected to happen:**
I expected the info tab to only show up when checking the recipes/uses for sticks or pistons.
###  **What happened:**
The info tab appears for any recipe I look up, not just for sticks or pistons.  Also, clicking the info tab also doesn't take you to the item in question, but instead starts you on a set page.  You then have to scroll or click next page to get to the info.

Keep up the good work though!  This is exactly the kind of mod I was looking for.  Simple and clean. 😄

**Comment by GoryMoon** [comment]
This was a miss frim me, I've now fixed and released this as 1.0.1.
