### ISSUE TITLE
Referencing Potions & Enchanted Books

### ISSUE THREAD

**Issue by DumbXBoxAcct** [GoryMoon/InfoDataPack#14]
First of all, I love this mod!  It really enhances JEI's extensibility in a **big** way.

One small issue I'm having though - and it's probably user error - is that I can't seem to add a tooltip or Info page to JEI for a potion or enchanted book, no matter how I try to reference them as items in Info DataPack.  Since they're similar concepts in terms of tags, I'm guessing that once you know how to reference one, you can reference the other, so I won't go through everything I've tried but, for instance, these variations for potions didn't work (I'm on IDP 4.0.0.14 & Forge 47.1.0):

"potion:"minecraft:strong_regeneration""
"potion:'minecraft:strong_regeneration'"
"minecraft:potion",tag:{Potion:"minecraft:strong_regeneration"}
"potion:{"minecraft:strong_regeneration"}"
"potion:{minecraft:strong_regeneration}"
"potion:minecraft:strong_regeneration"

Also wanted to mention that Just Enough Advancements 1.20.1-5.0.1, when run on Forge 47.1.0, with InfoDatapack 4.0.0.14 seems to knock out any Info tabs created with Info Datapack.  Tried loading IDP with JEA and without it, and the tabs are there without it, but appear to be replaced by a JEA tab when JEA is loaded.

And thank you for any help you that can offer on referencing potions & enchanted books.

**Comment by GoryMoon** [comment]
I've added some examples on how to do the potions and NBT overall here: https://github.com/GoryMoon/InfoDataPack/blob/main/example_datapack/data/example_pack/jei_info/nbt.json

I've also identified the issue with JEA and should have a version for it soon.
