### ISSUE TITLE
[Question] Different Tooltips dependant on absence of Enchantment?

### ISSUE THREAD

**Issue by DrVurruct** [GoryMoon/InfoDataPack#17]
Essentially, I'm trying to do unique Tooltips for Bows per Level of the Power Enchantment. This is completely doable up until having no enchantment on the Bow.

I believe I am suffering from user error, but it just seems to not work. As it stands, I have a separate Tooltip json per Level of Power. Trying to finagle the absence of power seems to be impossible. I am very tired right now, sorry if that is rambly. This is also my very first Github interaction ever, but I'm just unable to figure this out.

**Comment by GoryMoon** [comment]
Currently the only thing I could think of you being able to do is to check if there is no enchantments at all, not if a specific one is missing.

I would need to add an inverted check for that to work I think.

**Comment by GoryMoon** [comment]
This is now possible in 4.0.2.16, have a look at the example datapack and the [README.md](https://github.com/GoryMoon/InfoDataPack/blob/main/README.md)
