### ISSUE TITLE
JSON file path in Datapack

### ISSUE THREAD

**Issue by rckymtnrfc** [GoryMoon/InfoDataPack#2]
What's the correct path in the datapack for the json files?  I tried the root folder, assets and data and it doesn't seem to work.  Using your example code, so it shouldn't be a code issue.

Thanks

**Comment by GoryMoon** [comment]
The correct structure would be the same as zipping the content inside https://github.com/GoryMoon/InfoDataPack/tree/main/example_datapack
Replacing `example_datapack` with your own datapack name
