### ISSUE TITLE
[Bug] Playing with Crafttweaker + JEITweaker overrides this mod

### ISSUE THREAD

**Issue by RepeatGitHub** [GoryMoon/InfoDataPack#8]
I've been using the 1.18.2 version of this mod in my game for some time, and noticed that the Information tab isn't available when I have Crafttweaker and JEITweaker installed. Whether this is due to JEITweaker or Crafttweaker itself, I'm unsure, but it's a major issue for sure.

**Comment by GoryMoon** [comment]
I tested with the latest version of CraftTweaker, JEITweaker and JEI (didn't have any scripts set up in CraftTweaker tough) and the information tab showed with my example datapack.

If you could provide a minimum reproducible script setup or versions I could look into it again.
